In [1]:
import time
import numpy as np

In [2]:
x = np.random.random(100000000)

In [3]:
print(type(x))
print(len(x))

<class 'numpy.ndarray'>
100000000


In [4]:
start = time.time()
sum(x)/len(x)
print(time.time()-start)

16.71804165840149


### Benefits of using NumPy
Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists. Below are a few convincingly strong features:

1. One such feature is __speed__. When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

2. Another great feature of NumPy is that it has __multidimensional array data structures__ that can represent vectors and matrices. You will learn all about vectors and matrices in the Linear Algebra section of this course later on, and as you will soon see, a lot of machine learning algorithms rely on matrix operations. For example, when training a Neural Network, you often have to carry out many matrix multiplications. NumPy is optimized for matrix operations and it allows us to do Linear Algebra operations effectively and efficiently, making it very suitable for solving machine learning problems.

3. Another great advantage of NumPy over Python lists is that NumPy has a large number of __optimized built-in mathematical functions__. These functions allow you to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.


These are just some of the key features that have made NumPy an essential package for scientific computing in Python. In fact, NumPy has become so popular that a lot of Python packages, such as Pandas, are built on top of NumPy.

## Creating and saving numpy arrays

In [1]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
x.dtype

dtype('int32')

In [6]:
x.shape

(5,)

Notice `x.dtype` and `type(x)` gives different result.  
`type(x)` gives the type of array x.  
`x.dtype` gives the type of elements in the array x. It tells us that elements of x are stored in memory as signed 64-bit integers.

`x.shape` - This attribute returns a tuple and specifies the size of each dimension (i.e, number of elements) as an integer.

If we had a 2-dimensional array the shape attribute would return a tuple with two values - one for the number of rows and one for the number of columns.

In [3]:
Y = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # creating a 2D numpy array with nested python list
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
Y.shape  # 4 number of rows and 3 number of columns

(4, 3)

In [5]:
Y.size    # shows the total elements in Y

12

In general, we say that an array with n-dimensions has a rank n. So, the 1-D array `x` we created earlier can be referred to as a rank 1 array. And the 2-D array `Y` can be referred to as as rank 2 array.

Create a 1-D array `x2` with string elements.

In [7]:
x2 = np.array(['Hello', 'World'])
print(x2)

['Hello' 'World']


In [8]:
print('Shape of array x2: ', x2.shape)
print('Type of array x2: ', type(x2))
print('dtypes of x2: ', x2.dtype)

Shape of array x2:  (2,)
Type of array x2:  <class 'numpy.ndarray'>
dtypes of x2:  <U5


Observe dtype of this array is unicode string of 5 characters. So when numpy creates an array it automatically assigns its dtypes based on the type of the elements you used to create the array.

What happens when we create a numpy array from a list of integers and string data types? 

In [9]:
x3 = np.array([1,2,'Jeswin'])
print(x3)
print('Shape of array x3: ', x3.shape)
print('Type of array x3: ', type(x3))
print('dtypes of x3: ', x3.dtype)

['1' '2' 'Jeswin']
Shape of array x3:  (3,)
Type of array x3:  <class 'numpy.ndarray'>
dtypes of x3:  <U11


Notice all elements of the numpy array has been converted to strings - namely unicode strings of 21 characters.

Unlike python list, numpy array must contain elements of the same type.
  
If we create numpy array from a list of integers and floats. Numpy assign all element to float64 data type. This is called __Upcasting__. 

In [10]:
x4 = np.array([1,2.5,3])
print(x4)
print('Shape of array x4: ', x4.shape)
print('Type of array x4: ', type(x4))
print('dtypes of x4: ', x4.dtype)

[1.  2.5 3. ]
Shape of array x4:  (3,)
Type of array x4:  <class 'numpy.ndarray'>
dtypes of x4:  float64


Numpy also allows you to specify particular dtype you want to assign to elements of an array. Observe in the below example- numpy array has integer elements only even though we passed float elements to it.

In [13]:
x5 = np.array([1.4,2.5,3.2], dtype = np.int64)
print(x5)
print('Shape of array x5: ', x5.shape)
print('Type of array x5: ', type(x5))
print('dtypes of x5: ', x5.dtype)

[1 2 3]
Shape of array x5:  (3,)
Type of array x5:  <class 'numpy.ndarray'>
dtypes of x5:  int64


Specifying the data type is useful in those cases where we dont want to accidentally choose wrong data type or you want only certain amount of precision and want to save memory.

Numpy array can also be saved in a numpy file for future use - `np.save('my_array', x)` this will save the array as a `my_array.npy` file

In [14]:
x = np.array([1,2,3,4,5])
np.save('my_array',x)

Loading the __my_array.npy__ file using `np.load('my_array.npy')`.

In [15]:
y = np.load('my_array.npy')
y

array([1, 2, 3, 4, 5])