# Using Built-in Functions to Create ndarrays
One great time-saving feature of NumPy is it's ability to create ndarrays using built-in functions. These functions allow us to create certain kinds of ndarrays with just one line of code.

In [2]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

#### 1. `np.zeros(shape)`

The function `np.zeros(shape)` creates an ndarray full of `zeros` with the given `shape`. So, for example, if you wanted to create a rank 2 array with 3 rows and 4 columns, you will pass the shape to the function in the form of `(rows, columns)`.

In [3]:
X = np.zeros((3,4))
print('X = \n', X)
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


Can change the data type from __float__ to integers using `dtype` command.

In [4]:
X = np.zeros((3,4), dtype=np.int32)
print('X = \n', X)
print('The elements in X are of type:', X.dtype)

X = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The elements in X are of type: int32


#### 2. `np.ones(shape)`

In [5]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))
print('X = \n', X)
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


Can create a numpy array of ones with the help of __dtype__

In [6]:
X = np.ones((3,2), dtype = int)
print('X = \n', X)

X = 
 [[1 1]
 [1 1]
 [1 1]]


In addition to __ones__ and __zeros__ we can create an array filled with a constant value using `np.full(shape of array, constant)` function.

In [7]:
np.full((4,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#### 3. Identity matrices:  `np.eye(4)`
Its a square matrix. Has 1 as its diagonal elements and rest of the value are set as zero. 

In [8]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### 4. `np.diag([10,20,30,40])`
This function takes a sequence of values to be used in its diagonal and returns a square matrix. The remaining elements are kept as zero.

In [9]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

#### 5. Create a Numpy array of evenly spaced values in a given range, using `np.arange(stop_val)`

In [10]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)
# We print the ndarray
print('x = ', x)
# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x =  [0 1 2 3 4 5 6 7 8 9]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


When used with two arguments, `np.arange(start,stop)` will create a rank 1 ndarray with evenly spaced values within the half-open interval `[start, stop)`. This means the evenly spaced numbers will include `start` but exclude `stop`.

In [11]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)
print('x = ', x)

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x =  [4 5 6 7 8 9]
x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


Finally, when used with three arguments, `np.arange(start,stop,step)` will create a rank 1 ndarray with evenly spaced values within the half-open interval `[start, stop)` with step being the distance between two adjacent values.

In [12]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)
print('x = ', x)

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x =  [ 1  4  7 10 13]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


#### 6. `numpy.linspace()`

```
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```

It returns `num` evenly spaced values calculated over the interval `[start, stop]`.

Even though the `np.arange()` function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function `np.linspace()`.

The `np.linspace(start, stop, N)` function returns `N` evenly spaced numbers over the closed interval `[start, stop]`. This means that both the start and the stop values are included. 

In this case, the default number of elements in the specified interval will be `N= 50`. The reason `np.linspace()` works better than the `np.arange()` function, is that `np.linspace()` uses the number of elements we want in a particular interval, instead of the step between values.

In [13]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25. stop - inclusive
x = np.linspace(0,25,10)

print('x = \n', x)
# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [14]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25. Stop - excluded
x = np.linspace(0,25,10, endpoint=False)
print('x = \n', x)

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


#### 7. `numpy.reshape()` - Function
```
numpy.reshape(array, newshape, order='C')[source]
```

It gives a new shape to an array without changing its data. More details about the arguments are available [here](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape).

The `np.reshape(ndarray, new_shape)` function converts the given ndarray into the specified `new_shape`. It is important to note that the `new_shape` should be compatible with the number of elements in the given __ndarray__. 

For example, you can convert a rank 1 ndarray with 6 elements, into a 3 x 2 rank 2 ndarray, or a 2 x 3 rank 2 ndarray, since both of these rank 2 arrays will have a total of 6 elements. However, you can't reshape the rank 1 ndarray with 6 elements into a 3 x 3 rank 2 ndarray, since this rank 2 array will have 9 elements, which is greater than the number of elements in the original ndarray.

In [15]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
print('Original x = ', x)
# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))
print('Reshaped x = \n', x)
# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


#### 8. `numpy.ndarray.reshape` - This one is a Method.

```
ndarray.reshape(shape, order='C')
```
It returns an array containing the same data with a new shape. More details about the arguments are available [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape).

One great feature about NumPy, is that some functions can also be applied as methods. This allows us to apply different functions in sequence in just one line of code. ndarray methods are similar to ndarray attributes in that they are both applied using dot notation (`.`).

In [16]:
# Create a Numpy array by calling the reshape() function from the output of arange() function.
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)
print('Y = \n', Y)
# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 

Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


#### 9. `numpy.random.random()`

The last type of ndarrays we are going to create are random ndarrays. Random ndarrays are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing the weights of a Neural Network. NumPy offers a variety of random functions to help us create random ndarrays of any shape.

In [17]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))
print('X = \n', X)
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X = 
 [[0.64064267 0.52316792 0.24152944]
 [0.36992111 0.45181533 0.06487635]
 [0.63843685 0.33070793 0.40149135]]
X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


#### 10. `np.random.randint(start, stop, size = shape)`

NumPy also allows us to create ndarrays with random integers within a particular interval. The function `np.random.randint(start, stop, size = shape)` creates an ndarray of the given shape with random integers in the half-open interval `[start, stop)`.



In [18]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

print('X = \n', X)

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 4 10]
 [ 9  8]
 [10 11]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


#### 11. `np.random.normal(mean, standard deviation, size=shape)`
In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create random ndarrays with numbers drawn from various probability distributions.

The function `np.random.normal(mean, standard deviation, size=shape)`, for example, creates an ndarray with the given shape that contains random numbers picked from a __normal (Gaussian) distribution__ with the given __mean and standard deviation__. 

Let's create a 1000 x 1000 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

In [20]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))
# print('X = \n', X)
# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -8.099954123858115e-05
The maximum value in X is: 0.5120364830173553
The minimum value in X is: -0.46634576882534073
X has 500294 negative numbers
X has 499706 positive numbers


As we can see, the average of the random numbers in the ndarray is close to zero, both the maximum and minimum values in __X__ are symmetric about zero (the average), and we have about the same amount of positive and negative numbers.

Difference between a function and a method

![](1.PNG)