## Accessing, Deleting, and Inserting Elements Into ndarrays

- NumPy ndarrays are mutable, meaning that the elements in ndarrays can be changed after the ndarray has been created.
- NumPy ndarrays can also be sliced, which means that ndarrays can be split in many different ways. This allows us, for example, to retrieve any subset of the ndarray that we want. 
Often in Machine Learning you will use slicing to separate data, as for example when dividing a data set into training, cross validation, and testing sets.


#### 1. Access individual elements of 1-D array

In [1]:
import numpy as np

The same element can be accessed using both positive and negative indices.

In [2]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])
print('x = ', x)
# Let's access some elements with positive indices
print('This is First Element in x:', x[0]) 
print('This is Fifth (Last) Element in x:', x[4])
# Let's access the same elements with negative indices
print('This is Fifth (Last) Element in x:', x[-1])

x =  [1 2 3 4 5]
This is First Element in x: 1
This is Fifth (Last) Element in x: 5
This is Fifth (Last) Element in x: 5


#### 2. Modify an element of 1-D array

In [3]:
x = np.array([1, 2, 3, 4, 5])
print('Original:\n x = ', x)
# We change the fourth element in x from 4 to 20
x[3] = 20
# We print x after it was modified 
print('Modified:\n x = ', x)

Original:
 x =  [1 2 3 4 5]
Modified:
 x =  [ 1  2  3 20  5]


#### 3. Access individual elements of 2-D array
To access elements in rank 2 ndarrays we need to provide 2 indices in the form `[row, column]`.

In [4]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('X = \n', X)
# Let's access some elements in X
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


#### 4. Modify an element of 2-D array

In [5]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original:\n X = \n', X)
# We change the (0,0) element in X from 1 to 20
X[0,0] = 20

# We print X after it was modified 
print('Modified:\n X = \n', X)

Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


#### 5. Delete elements
We can delete elements using the `np.delete(ndarray, elements, axis)` function. This function deletes the given list of elements from the given ndarray along the specified axis. For rank 1 ndarrays the axis keyword is not required.  
For rank 2 ndarrays:
> `axis = 0` is used to select rows, and `axis = 1` is used to select columns.

In [6]:
x = np.array([1, 2, 3, 4, 5])
print('Original x = ', x)
x = np.delete(x, [0,4])  # Delete the 0th and 4th element
print('Modified x = ', x)

Original x =  [1 2 3 4 5]
Modified x =  [2 3 4]


In [7]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Original Y = \n', Y)
# We delete the first row of y
w = np.delete(Y, 0, axis=0)
print('Delete the first row of y = \n', w)


# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)
print('Delete the first and last column of y = \n', v)

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Delete the first row of y = 
 [[4 5 6]
 [7 8 9]]
Delete the first and last column of y = 
 [[2]
 [5]
 [8]]


#### 6. `numpy.append()`

```
numpy.append(array, values, axis=None)
```
It appends values to the end of an array.   
We can append values to ndarrays using the `np.append(ndarray, elements, axis)` function. This function appends the given list of `elements` to `ndarray` along the specified `axis`. 

In [8]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])
print('Original x = ', x)
# We append the integer 6 to x
x = np.append(x, 6)
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])
print('x = ', x)

Original x =  [1 2 3 4 5]
x =  [1 2 3 4 5 6]
x =  [1 2 3 4 5 6 7 8]


In [10]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])
print('Original Y = \n', Y)
# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)
print('append a new row containing 7,8,9 = \n', v)
# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)
print('append a new column containing 9 and 10 = \n', q)

Original Y = 
 [[1 2 3]
 [4 5 6]]
append a new row containing 7,8,9 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
append a new column containing 9 and 10 = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


#### 7. Insert elements

We can insert values to ndarrays using the `np.insert(ndarray, index, elements, axis)` function.  
This function inserts the given list of `elements` to `ndarray` right before the given `index` along the specified `axis`.

In [11]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])
print('Original x = ', x)
# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

print('x with the inserted elements = ', x)


Original x =  [1 2 5 6 7]
x with the inserted elements =  [1 2 3 4 5 6 7]


In [12]:
Y = np.array([[1,2,3],[7,8,9]])
print('Original Y = \n', Y)
# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)
print('insert a row between the first and last row of y = \n', w)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)
print('insert a column full of 5s between the first and second column of y = \n', v)

Original Y = 
 [[1 2 3]
 [7 8 9]]
insert a row between the first and last row of y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
insert a column full of 5s between the first and second column of y = 
 [[1 5 2 3]
 [7 5 8 9]]


#### 8. `numpy.hstack and numpy.vstack`

```
numpy.hstack(sequence_of_ndarray)
```

It returns a stacked array formed by stacking the given arrays in sequence horizontally (column-wise). See the in-depth details [here](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html).

```
numpy.vstack(sequence_of_ndarray)
```

It returns a stacked array formed by stacking the given arrays, will be at least 2-D, in sequence vertically (row-wise). See the in-depth details [here](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html).

NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. The stacking is done using either the `np.vstack()` function for vertical stacking, or the `np.hstack()` function for horizontal stacking. It is important to note that in order to stack ndarrays, the shape of the ndarrays must match. 

In [13]:
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])
print('x = ', x)
print('Y = \n', Y)
# We stack x on top of Y
z = np.vstack((x,Y))
print('vstack: stack x on top of Y = \n', z)

x =  [1 2]
Y = 
 [[3 4]
 [5 6]]
vstack: stack x on top of Y = 
 [[1 2]
 [3 4]
 [5 6]]


In [15]:
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])
print('x = ', x)
print('Y = \n', Y)
# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))
print('Reshaped x = \n', x.reshape(2,1))
print('hstack: stack x on the right of Y = \n', w)

x =  [1 2]
Y = 
 [[3 4]
 [5 6]]
Reshaped x = 
 [[1]
 [2]]
hstack: stack x on the right of Y = 
 [[3 4 1]
 [5 6 2]]
