# Slicing ndarrays

NumPy provides a way to access subsets of ndarrays. This is known as slicing. Slicing is performed by combining indices with the colon `:` symbol inside the square brackets. In general you will come across three types of slicing:

```
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]
```

#### 1. Slicing in a 2-D ndarray

In [26]:
import numpy as np
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print('X = \n', X)
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [27]:
# We can select the same elements as above using method 2
W = X[1:,2:5]
print('W = \n', W)

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [28]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]
print('Y = \n', Y)

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [29]:
# We select all the elements in the 3rd row
v = X[2,:]
print('v = ', v)

v =  [10 11 12 13 14]


In [30]:
# We select all the elements in the 3rd column
q = X[:,2]
print('q = ', q)

q =  [ 2  7 12 17]


In [31]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

print('R = \n', R)

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


Notice that when we selected all the elements in the 3rd column, variable `q= X[:,2]` above, the slice returned a rank 1 ndarray instead of a rank 2 ndarray.  However, slicing `X` in a slightly different way, variable `R= X[:,2:3]` above, we can actually get a rank 2 ndarray instead.

__It is important to note that when we perform slices on ndarrays and save them into new variables, as we did above, the data is not copied into the new variable.__

> slicing only creates a view of the original array.

In [32]:
Z = X[1:4,2:5]
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


The slice of the original array X is not copied in the variable Z. Rather, X and Z are now just two different names for the same ndarray. We say that slicing only creates a view of the original array. 

__This means that if you make changes in Z you will be in effect changing the elements in X as well.__  
 Let's see this with an example:

In [33]:
Z[0,2] = 1000
print(Z)

[[   7    8 1000]
 [  12   13   14]
 [  17   18   19]]


In [34]:
print("Updated value of X: \n", X)

Updated value of X: 
 [[   0    1    2    3    4]
 [   5    6    7    8 1000]
 [  10   11   12   13   14]
 [  15   16   17   18   19]]


Observe the value of 1000 in both __Z__ and __X__.

#### 2. numpy.ndarray.copy

```
ndarray.copy(order='C')
```

It returns a copy of the array.

If we want to create a new ndarray that contains a copy of the values in the slice we need to use the `np.copy()` function. The `np.copy(ndarray)` function creates a copy of the given ndarray.

This function can also be used as a method, in the same way as we did before with the reshape function.

__We'll use `copy` both as a function and as a method.__

##### Demonstrate the `copy()` function

In [36]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

# We change the last element in Z to 555
Z[2,2] = 555

print('X = \n', X)
print('Z = \n', Z)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [37]:
#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()
# We change the last element in W to 444
W[2,2] = 444
print('X = \n', X)
print('W = \n', W)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


We can clearly see that by using the `copy` command, we are creating new ndarrays that are completely independent of each other.

It is often useful to use one ndarray to make slices, select, or change elements in another ndarray.

#### 3. Use an array as indices to either make slices, select, or change elements



In [38]:
X = np.arange(20).reshape(4, 5)
indices = np.array([1,3])
print('X = \n', X)
print('indices = ', indices)

# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[indices,:]
print('Y = \n', Y)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
indices =  [1 3]
Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [39]:
# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, indices]
print('X = \n', X)
print('indices = ', indices)
print('Z = \n', Z)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
indices =  [1 3]
Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


#### 4. Use an array as indices to extract specific rows from a rank 2 ndarray.



In [40]:
# Let's create a rank 2 ndarray
X = np.random.randint(1,20, size=(50,5))
print("Shape of X is: ", X.shape)

Shape of X is:  (50, 5)


In [41]:
# Create a rank 1 ndarray that contains a randomly chosen 10 values between `0` to `len(X)` (50)
# The row_indices would represent the indices of rows of X
row_indices = np.random.randint(0,50, size=10)
print("Random 10 indices are: ", row_indices)

Random 10 indices are:  [49  6 37 22 32 37  1 26 19 40]


In [42]:
# To Do 1 - Print those rows of X whose indices are represented by entire row_indices ndarray
# Hint - Use the row_indices ndarray to select specified rows of X
X_subset = X[row_indices, :]
print(X_subset)

[[19 17  5  5  5]
 [11 14 17  3 14]
 [ 2  6 15 14  4]
 [ 9 13  5 13  9]
 [ 9  2 12 11  1]
 [ 2  6 15 14  4]
 [ 8  5  9 13  1]
 [12  5 16 16 14]
 [ 2  8  7  7 14]
 [10 18 13 13  9]]


In [43]:
# To Do 2 - Print those rows of X whose indices are present in row_indices[4:8]
X_subset = X[row_indices[4:8], :]
print(X_subset)

[[ 9  2 12 11  1]
 [ 2  6 15 14  4]
 [ 8  5  9 13  1]
 [12  5 16 16 14]]


#### 5. `numpy.diag`

```
numpy.diag(array, k=0)
```

It extracts or constructs the diagonal elements.

NumPy also offers built-in functions to select specific elements within ndarrays. For example, the `np.diag(ndarray, k=N)` function extracts the elements along the `diagonal` defined by `N`. As default is `k=0`, which refers to the main diagonal. Values of `k > 0` are used to select elements in diagonals above the main diagonal, and values of `k < 0` are used to select elements in diagonals below the main diagonal. 

In [46]:
# We create a 4 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)
print('X = \n', X)
# We print the elements in the main diagonal of X
print('Main diagonal elements z =', np.diag(X))

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Main diagonal elements z = [ 0  6 12 18 24]


In [47]:
# We print the elements above the main diagonal of X
print('the diagonal elements above the main diagonal of X =', np.diag(X, k=1))

the diagonal elements above the main diagonal of X = [ 1  7 13 19]


In [48]:
# We print the elements below the main diagonal of X
print('elements below the main diagonal of X = ', np.diag(X, k=-1))

elements below the main diagonal of X =  [ 5 11 17 23]


#### 6. `numpy.unique`

```
numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)
```

It returns the sorted unique elements of an array. 

It is often useful to extract only the unique elements in an ndarray. We can find the unique elements in an ndarray by using the `np.unique()` function. The `np.unique(ndarray)` function returns the unique elements in the given `ndarray`.

In [49]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print('X = \n', X)

# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]
The unique elements in X are: [1 2 3 5 8]
